kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx_pod_1
  template:
    metadata:
      labels:
        app: nginx_pod_1
    spec:
      containers:
      - name: simple-http
        image: registry.kurlycorp.kr/baseimages/nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
