#kind: Deployment
#apiVersion: apps/v1
kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx-pod-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-1
  template:
    metadata:
      labels:
        app: nginx-pod-1
    spec:
      containers:
      - name: nginx-pod-1
        image: registry.kurlycorp.kr/baseimages/nginx:5
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
  strategy:
  # ----- Everything above this comment are the same as a deployment -----
    blueGreen: # A new field for the Blue Green strategy options
      previewService: nginx-pod-1-prv # Reference to a service
      activeService: nginx-pod-1 # Reference to a service
      autoPromotionEnabled: true
      autoPromotionSeconds: 60
      previewReplicaCount: 1
      scaleDownDelaySeconds: 60  #전환후 이전 active pod 삭제 대기 시간
