apiVersion: v1
kind: Service
metadata:
  name: clusterip-service-1
spec:
  selector:
    app: nginx_pod_1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: clusterip-service-3
#spec:
#  selector:
#    app: nginx_pod_3
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
