#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-pod-1
#spec:
#  selector:
#    app: nginx-pod-1
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-pod-1
    service: nginx-pod-1
  name: nginx-pod-1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-pod-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-pod-1-prv
    service: nginx-pod-1-prv
  name: nginx-pod-1-prv
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-pod-1
